# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

    config.vm.define "k8s-master" do |server|
        server.vm.box = "ubuntu-22.04"
        server.vm.hostname = "k8s-master"
        # server.vm.network "private_network", ip: "172.16.1.10"
        server.vm.provider "virtualbox" do |vm|
            vm.name = "k8s-master"
            vm.memory = 4096
            vm.cpus = 4
            vm.customize ["modifyvm", :id, "--nic3", "natnetwork", "--nat-network3", "natnet4"]
        end
    end

    WorkerInstance=1
    (1..WorkerInstance).each do |i|
        config.vm.define "k8s-worker-#{i}" do |server|
            server.vm.box = "ubuntu-22.04"
            server.vm.hostname = "k8s-worker-#{i}"
            # server.vm.network "private_network", ip: "172.16.1.1#{i}"
            server.vm.provider "virtualbox" do |vm|
                vm.name = "k8s-worker-#{i}"
                vm.memory = 4096
                vm.cpus = 4
                vm.customize ["modifyvm", :id, "--nic3", "natnetwork", "--nat-network3", "natnet4"]
            end
        end
    end

    config.ssh.username = "root"
    config.ssh.password = "root"

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
    end

end
